# Generated by Django 4.2.23 on 2025-06-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('doc_file', models.FileField(upload_to='templates_docs/')),
            ],
        ),
        migrations.DeleteModel(
            name='DocTemplate',
        ),
    ]
